language: java
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: "marmer-github"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-${MAVEN_VERSION}"
  - "$HOME/.sonar/cache"
before_cache:
- rm -rfv $HOME/.m2/repository/io/github/marmer
before_install:
- export M2_HOME=$HOME/apache-maven-${MAVEN_VERSION}
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH
install:
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -B -V -U
script:
- mvn jacoco:prepare-agent package sonar:sonar -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -V
after_success:
- mvn clean deploy -Dmaven.test.skip --settings server-settings.xml
